baseurl = "http://deleeuwpdx.net/"
title = "Jan's Page"
author = "Jan de Leeuw"
copyright = "Copyright (c) 2016 Marcus Brinkmann"
canonifyurls = true
paginate = 3
theme = "hugo-finite"
math = true
highlight = false

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "2006-01-02"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

bio_full = "Jan de Leeuw: retired, not finished"
bio_twitter = "deleeuw_jan"

# Title of posts section on main page.
# posts_title = "Posts"

# Number of posts to show on main page.
# posts_count = 5

# Title of publications section on main page.
# pubs_title = "Papers"

# Number of publications to show on main page.
# pubs_count = 8

[[params.education]]
  course = "Ph.D. Social Sciences"
  institution = "Leiden University"
  year = 1973

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:jan@deleeuwpdx.net"
  text = "jan@deleeuwpdx.net"    

[[params.social]]
  icon = "facebook"
  icon_pack = "fa"
  link = "https://www.facebook.com/jan.deleeuw.31521"
  text = "Jan"
  site = "Facebook"    

[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/deleeuwpdx"
  text = "Jan"
  site = "Twitter"    

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/deleeuw"
  text = "Jan"
  site = "GitHub"

[[params.social]]
  icon = "researchgate"
  icon_pack = "ai"
  link = "https://www.researchgate.net/profile/Jan_De_Leeuw"
  text = "Jan"
  site = "ResearchGate"

[[params.social]]
  icon = "academia"
  icon_pack = "ai"
  link = "https://ucla.academia.edu/JanDeLeeuw"
  text = "Jan"
  site = "Academia"

[[params.social]]
  icon = "university"
  icon_pack = "fa"
  link = "https://www.knaw.nl/en/members/correspondents/4449"
  text = "Jan"
  site = "KNAW"

[[params.social]]
  icon = "wikipedia-w"
  icon_pack = "fa"
  link = "https://en.wikipedia.org/wiki/Jan_de_Leeuw"
  text = "Jan"
  site = "Wikipedia"

[[params.social]]
  icon = "google-scholar"
  icon_pack = "ai"
  link = "https://scholar.google.com/citations?user=Ccp--gIAAAAJ&hl=en"
  text = "Jan"
  site = "Google Scholar"

[[params.social]]
  icon = "university"
  icon_pack = "fa"
  link = "https://www.genealogy.math.ndsu.nodak.edu/id.php?id=36682&fChrono=1"
  text = "Jan"
  site = "Mathematics Genealogy"

[[params.social]]
  icon = "archive"
  icon_pack = "fa"
  link = "https://archive.org/details/@deleeuw?sort=-date"
  text = "Jan"
  site = "Internet Archive"

[[params.social]]
  icon = "file-audio-o"
  icon_pack = "fa"
  link = "https://drive.google.com/open?id=0B3XRUQgTUKEMVEpENHNOYzNVZm8"
  text = "Pronounce My First Name"

[[params.social]]
  icon = "file-audio-o"
  icon_pack = "fa"
  link = "https://drive.google.com/open?id=0B3XRUQgTUKEMTERXMFRJeDJqR2M"
  text = "Pronounce My Last Name"

# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 1

[[menu.main]]
  name = "Publications"
  url = "/publication/"
  weight = 2

[[menu.main]]
  name = "Bibliography"
  url = "http://deleeuwpdx.net/janspubs/0_bib_material"
  weight = 3

[[menu.main]]
  name = "Piedmont History"
  url = "https://drive.google.com/open?id=1efOTXOGHw3DVqBCZ_prTYZ1GU9jfaRfXDsiy3-QLyS8"
  weight = 4

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 5

