baseurl = "/"
title = "Jan's Page"
author = "Marcus Brinkmann"
copyright = "Copyright (c) 2016 Marcus Brinkmann"
canonifyurls = true
paginate = 3
theme = "hugo-finite"

[params]

# Date format (refer to Go's date format: http://flippinggodateformat.com)
# Examples: "Mon, Jan 2, 2006" or "2006-01-02"
date_format = "2006-01-02"

# Publications can have a Params.publication for citation references.
# Publications can have a Params.kind, such as "book".
# Both parameters are mapped to an icon in partials/pub-icon.html.

bio_full = "Jan de Leeuw: retired, not finished"
bio_twitter = "deleeuw_jan"

# Title of posts section on main page.
#posts_title = "Posts"

# Number of posts to show on main page.
#posts_count = 1

# Title of publications section on main page.
#pubs_title = "Publications"

# Number of publications to show on main page.
#pubs_count = 5

[[params.education]]
  course = "Ph.D. Social Sciences"
  institution = "Leiden University"
  year = 1973

[[params.social]]
  icon = "envelope"
  icon_pack = "fa"
  link = "mailto:deleeuw@stat.ucla.edu"
  text = "deleeuw@stat.ucla.edu"
    
[[params.social]]
  icon = "twitter"
  icon_pack = "fa"
  link = "https://twitter.com/deleeuw_jan"
  text = "@deleeuw_jan"
  site = "Twitter"

[[params.social]]
  icon = "facebook"
  icon_pack = "fa"
  link = "https://www.facebook.com/jan.deleeuw1"
  text = "jan.deleeuw1"
  site = "Facebook"

[[params.social]]
  icon = "github"
  icon_pack = "fa"
  link = "https://github.com/deleeuw"
  text = "deleeuw"
  site = "GitHub"

[[params.social]]
  icon = "researchgate"
  icon_pack = "ai"
  link = "https://www.researchgate.net/profile/Jan_De_Leeuw"
  text = "ResearchGate"



# Navigation Links
# The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Publications"
  url = "/publication/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 3

[[menu.main]]
  name = "Contact"
  url = "/#contact"
  weight = 4

